### ISSUE TITLE
Error in remote browser

### ISSUE THREAD

**Issue by john65537** [Yubico/php-u2flib-server#17]
I installed U2F server library on CentOS 7, it works well with Chrome on the Local machine.
But when I try to test the U2F server with a remote Chrome, ie. connecting from different IP,
U2F server seemed unable to communicate with the Chrome thus responded with an error code: 2.
This problem also exists in the Java version of U2F server library. 
The same Chrome works well at Yubico's Demo site and Google+ with a U2F token.
Could you please explain why does this error happen and how to resolve it?
Thanks!

**Comment by minisu** [comment]
This is probably because the URL that Chrome is visiting is not matching the server's App ID. In the PHP demo server, App ID defaults to `$_SERVER['HTTP_HOST']` and in the Java demo server it defaults to `localhost:8080`.

The App ID is part of what makes U2F phishing resistant. Read more about this here: [Using a U2F library](https://developers.yubico.com/U2F/Libraries/Using_a_library.html) | [App ID](https://developers.yubico.com/U2F/App_ID.html)

**Comment by john65537** [comment]
Thank you for helping, but I still can't solve it.
When I tested Php U2F Server locally using a URL beginning with IP instead of localhost, the same error code:2 was returned. If I use a URL of 'localhost' as before then everything works well.
Any suggestion?

**Comment by minisu** [comment]
That's expected (but probably not very well documented). IP-addresses cannot be part of an App ID for this reason:

> in addition to being challenging to parse, we'd have to reason
through all sorts of equivalency issues. For example, are two different
representations of the same IP address considered the same or not? What
about virtual hosts on the same IP?

If you want to access the server from another machine in the internal network, you can edit the hosts file of the client machine, adding the line `192.168.53.97 example.com`.

Maybe a way to avoid trouble with this is to make php-u2flib-server validate the App ID when the server is started (showing warnings if IP-addresses are used or if HTTPS is not used, etc.).

**Comment by john65537** [comment]
Great!
The way of editing hosts file succeeded in php-u2flib-server, no need to modify App ID, since PHP version uses $_SERVER['HTTP_HOST'] instead of a fixed one.
Now I can demonstrate U2F server decently to my team members. Many thanks!

However, FIDO limits a server IP being used as App ID sounds reasonable, but seems different with SSL rules. SSL Certificates accept server IP for authentication. This confused me a little.

**Comment by john65537** [comment]
Dear Henrik,

Thank you for your help with my U2F issue on GitHub.

At this moment I and my colleague are working on plotting a FIDO solution
with a FIDO Ready smartphone—Samsung S5.

Since there is no open source project on UAF to date, I am considering
modifying a U2F open source project and obtain the UAF compatibility.

I guess it should be possible for the server side to do this kind of
adaption, but on client side I wonder whether a UAF authenticator can be
used as a U2F authenticator? Is it possible for a UAF authenticator like
Samsung S5 being used as a U2F authenticator?


Best regards,
John

2015-02-26 15:10 GMT+08:00 Henrik Stråth <notifications@github.com>:

**Comment by minisu** [comment]
Hi John,

Unfortunately, you cannot use a UAF authenticator as a U2F authenticator.

**Comment by john65537** [comment]
Thanks for the concise answer.

If I develop a software U2F authenticator on top of a hardware UAF
authenticator, will this structure achieve my goal?

Best regards,
John

2015-04-20 16:41 GMT+08:00 Henrik Stråth <notifications@github.com>:

**Comment by minisu** [comment]
No, that's not possible.

Next time you have a U2F question not directly related to one of our libraries, please use on of these channels instead:
[fido-dev mailing list](https://groups.google.com/a/fidoalliance.org/forum/?utm_medium=email&utm_source=footer#!forum/fido-dev)
[Yubico forum](http://forum.yubico.com/)

**Comment by john65537** [comment]
Thanks.
I'll ask FIDO questions there.
I didn't mean to bother you, just couldn't find a proper place to ask.

Best regards,
John

2015-04-22 15:01 GMT+08:00 Henrik Stråth <notifications@github.com>:
