### ISSUE TITLE
Correct handling of errorCode 0

### ISSUE THREAD

**Issue by Dijky** [Yubico/php-u2flib-server#47]
This library expects a registration/authentication response to not contain the property `errorCode` (see [here](https://github.com/Yubico/php-u2flib-server/blob/master/src/u2flib_server/U2F.php#L146) and [here](https://github.com/Yubico/php-u2flib-server/blob/master/src/u2flib_server/U2F.php#L259)).

However, an `errorCode` value of *0* should be considered as *OK*.

This behaviour currently breaks functionality with (at least) Chrome for Android's implementation, which sets the property `errorCode` to *0* on success.

**Comment by Schottii** [comment]
I got the same problem. The weird thing is, that only my mobile generates error code 0.
Shouldn't be hard to fix.

Regards
