### ISSUE TITLE
Example not working in Firefox 60.1.0

### ISSUE THREAD

**Issue by Julian0815** [Yubico/php-u2flib-server#68]
Hi,

I would like to include u2f authentication to my homepage.

To start I tried to run the pdo example here.
If I try to register, I always get the following error in the js console in Firefox 60.1.0 (ESR):
``TypeError: setting getter-only property "u2f" : u2f-api.js:16:5``

Is the example broken or did I make some mistake?

Thanks
Julian

**Comment by mp-strachan** [comment]
Have you tried with Chrome or Opera? The PDO example works fine for me in those browsers, but not Firefox (61 or dev.63).

I think it has something to do with Firefox's implementation of the FIFO standard. Have a look near the end of this link:
https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/

**Comment by Julian0815** [comment]
Chrome just shows the first page where I can choose a username and having the options to register or authenticate.
If I choose a username, select register and click on Submit! just the same empty form appears again.
No error is shown in the javascript console or in the apache error.log.

If I'm trying to use https://demo.yubico.com/u2f everything is fine
