### ISSUE TITLE
Sample usage?

### ISSUE THREAD

**Issue by hackerfactor** [Yubico/php-u2flib-server#77]
Can you provide an explicit example for how to use this code?

E.g., I see cli.  It wants two parameters -r and -o, but doesn't tell me what they are or what they do.

If I run the server "./u2f-server.phps -o ff -r mytest", I see a line of JSON output.  Then it sits. I have no idea what it's waiting for as input. But if I type in anything (clearly what it doesn't expect), it throws an error about doRegister only accepting objects. (Error on U2F.php line 167).

**Comment by emlun** [comment]
Sorry we didn't respond. Since the U2F API is now obsolete, we're archiving this repository and ceasing maintenance of the library.
