### ISSUE TITLE
PHP Preloading incompatibility

### ISSUE THREAD

**Issue by PhilETaylor** [Yubico/php-u2flib-server#78]
I have proved that this script is INCOMPATIBLE with PHP 7 Preloading

The problem is with constants. 

The namespaces constants are removed when the script is preloaded. 

The solution I found was to move the constants into the class, so they become namespaced class constants.

**Comment by PhilETaylor** [comment]
My solution for now was to fork, and move the namespaced constants into the class 

https://github.com/PhilETaylor/php-u2flib-server/tree/1.0.3

**Comment by emlun** [comment]
Sorry we didn't respond. Since the U2F API is now obsolete, we're archiving this repository and ceasing maintenance of the library.
